#!/bin/bash -e

name: Build-macos

on:
  push:
    branches: [ rewrite ]
  pull_request:
    branches: [ rewrite ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set execute permissions
        run: chmod +x ./scripts/build-macos.sh

      - name: Debug
        run: |
          pwd
          ls -la

      - name: Build and package x64 and arm64 version for macOS
        run: sh ./scripts/build-macos.sh

      - name: Upload artifacts (arm64)
        uses: actions/upload-artifact@v2
        with:
          name: MultiRPC-arm64.app
          path: ./macOS Templates/MultiRPC-arm64.app

      - name: Upload artifacts (x64)
        uses: actions/upload-artifact@v2
        with:
          name: MultiRPC-x64.app
          path: ./macOS Templates/MultiRPC-x64.app
