name: Build-macos

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build and package x64 and arm64 version for macOS
        run: sh build-macos.sh

      - uses: actions/upload-artifact@v2
        with:
          name: MultiRPC-arm64.app
          path: ./macOS Templates/MultiRPC-arm64.app

      - uses: actions/upload-artifact@v2
        with:
          name: MultiRPC-x64.app
          path: ./macOS Templates/MultiRPC-x64.app
